site:
  about:
    siteName: Nuclear Tech Mod Remake
    siteDescription: Documentation website of the Nuclear Tech Mod Remake.
Editorial:
  primaryColor: "#FFE000"
  legacySearch: false
  metaComponents:
    - type: "orchidSearch"
  social:
    github: "MartinTheDragon/Nuclear-Tech-Mod-Remake"
  menu:
    - type: "submenu"
      title: "Wiki"
      menu:
        - type: "wiki"
    - type: "page"
      itemId: "Changelog"
wiki:
  sections:
    - "userManual"
    - "developerGuide"
services:
  publications:
    stages:
      githubPages:
        branch: gh-pages
        repo: "Nuclear-Tech-Mod-Remake"
        username: 'MartinTheDragon'
