modLoader="javafml"
loaderVersion="[33,)"
license="GPL v3.0"
[[mods]]
modId="ntm"
version="0.0.1.0"
displayName="Nuclear Tech Mod Remake"
credits="HbM: Did well..."
authors="MartinTheDragon"
description='''All the high quality nuclear bombs and machinery you can only find in this mod or in the older 1.7.10 version!
The mod with both quantity and quality ;D
Inspired by HbMinecraft's Nuclear Tech Mod and recreated by MartinTheDragon.
'''
