contact_links:
    - name: NTM 1.18 Discord
      url: https://discord.gg/XDrARD2FaJ
      about: Just got a quick question? Join the Discord server dedicated to the 1.18 port, unaffiliated with the official NTM Discord.
