contact_links:
  - name: NTM 1.7.10 Discord Server
    url: https://discord.gg/ntm
    about: Just got a quick question about something? Maybe you can find help here. Please note though that this server is more familiar with the original 1.7.10 version of the mod. So try pinging @MartinTheDragon when you need something, and be aware I might not always have the time.
